import type { Metadata, Viewport } from "next";
import { SiteNav } from "@/app/components/SiteNav";
import { ThemeProvider } from "@/app/components/ThemeProvider";
import { PageTransition } from "@/app/components/motion/PageTransition";
import { DEFAULT_OG_IMAGE } from "@/lib/og";
import { FloatingCompanion } from "@/app/components/FloatingCompanion";
import { TactileLayer } from "@/app/components/TactileLayer";
import { SpatialLightCursor } from "@/app/components/motion/SpatialLightCursor";
import { ErrorBoundary } from "@/app/components/ErrorBoundary";
import { OfflineIndicator } from "@/app/components/OfflineIndicator";
// Font subsetting: Bundling only required weights (400, 600, 700) and critical
// styles; unused weights (300, 500, 300-italic, 700-italic) are omitted to reduce bundle size.
import "@fontsource/inter/latin-400.css";
import "@fontsource/inter/latin-600.css";
import "@fontsource/inter/latin-700.css";
import "@fontsource/merriweather/latin-400.css";
import "@fontsource/merriweather/latin-700.css";
import "@fontsource/merriweather/latin-400-italic.css";
import "@fontsource/noto-sans-devanagari/devanagari-400.css";
import "@fontsource/noto-sans-devanagari/devanagari-600.css";
import "@fontsource/noto-sans-devanagari/devanagari-700.css";
import "./globals.css";
import ServiceWorkerRegister from "./components/ServiceWorkerRegister";

/**
 * Inline script that runs synchronously before React hydrates so the
 * theme attribute is set on <html> in the first paint. Without this,
 * users would see a flash of the default (day) theme before the
 * ThemeProvider's useEffect runs and applies their stored preference.
 */
const THEME_INIT_SCRIPT = `
(function () {
  try {
    var t = localStorage.getItem('dharma-theme');
    if (t === 'sunset' || t === 'night' || t === 'day' || t === 'paper') {
      document.documentElement.setAttribute('data-theme', t);
    }
  } catch (e) {}
  // The home-page splash plays once per browser session; later page loads
  // skip it before first paint. Landing on any other page first also counts
  // as seen. Without storage it simply plays on each home-page load.
  try {
    var base = ${JSON.stringify(process.env.NEXT_PUBLIC_BASE_PATH || "")};
    var path = location.pathname;
    if (base && path.indexOf(base) === 0) path = path.slice(base.length);
    var isHome = path === '' || path === '/';
    if (sessionStorage.getItem('dharma-splash') || !isHome) {
      document.documentElement.setAttribute('data-splash', 'seen');
    }
    sessionStorage.setItem('dharma-splash', '1');
  } catch (e) {}
})();
`;

const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL || "https://dharmagranth.in";
const SITE_NAME = "Dharma Granth";
const DEFAULT_TITLE = "Dharma Granth — Hindu Scriptures, Verse by Verse";
const DEFAULT_DESCRIPTION =
  "Famous verses from the Bhagavad Gita, Upanishads, and other Hindu scriptures, explained verse by verse in Sanskrit, Hindi, and plain English. Free and ad-free.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: DEFAULT_TITLE,
    template: "%s — Dharma Granth",
  },
  description: DEFAULT_DESCRIPTION,
  applicationName: SITE_NAME,
  keywords: [
    "Bhagavad Gita",
    "Upanishads",
    "Hindu scripture",
    "Sanskrit verses",
    "Vedas",
    "Hindi commentary",
    "dharma",
    "verse meaning",
  ],
  authors: [{ name: "Dharma Granth" }],
  creator: "Dharma Granth",
  publisher: "Dharma Granth",
  openGraph: {
    type: "website",
    locale: "hi_IN",
    alternateLocale: ["en_US"],
    url: SITE_URL,
    siteName: SITE_NAME,
    title: DEFAULT_TITLE,
    description: DEFAULT_DESCRIPTION,
    images: [DEFAULT_OG_IMAGE],
  },
  twitter: {
    card: "summary_large_image",
    title: DEFAULT_TITLE,
    description: DEFAULT_DESCRIPTION,
    images: [DEFAULT_OG_IMAGE.url],
  },
  // Generated by `npm run og:build` (scripts/generate-og-images.ts).
  icons: {
    icon: [
      { url: "/favicon.svg", type: "image/svg+xml" },
      { url: "/icons/icon-32.png", sizes: "32x32", type: "image/png" },
    ],
    apple: [{ url: "/icons/apple-touch-icon.png", sizes: "180x180" }],
  },
  manifest: "/manifest.webmanifest",
  appleWebApp: {
    capable: true,
    title: SITE_NAME,
    statusBarStyle: "default",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
      "max-video-preview": -1,
    },
  },
  // Google Search Console ownership proof for https://dharmagranth.in/
  // (URL-prefix property). Env var overrides for other environments.
  verification: {
    google:
      process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION ||
      "YWMSMR_2e_0e1w2nqm5_sMRIgnkVNgF-6IRNRRdyYS4",
  },
  category: "religion",
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#c2410c" },
    { media: "(prefers-color-scheme: dark)", color: "#1a1412" },
  ],
  width: "device-width",
  initialScale: 1,
};

const siteJsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": `${SITE_URL}/#organization`,
      name: SITE_NAME,
      url: SITE_URL,
      // Square, per Google's logo guidelines (min 112×112). Built by
      // scripts/build-logo.mjs from assets/logo-source.webp.
      logo: `${SITE_URL}/logo.png`,
      image: `${SITE_URL}${DEFAULT_OG_IMAGE.url}`,
      description: DEFAULT_DESCRIPTION,
    },
    {
      "@type": "WebSite",
      "@id": `${SITE_URL}/#website`,
      url: SITE_URL,
      name: SITE_NAME,
      description: DEFAULT_DESCRIPTION,
      publisher: { "@id": `${SITE_URL}/#organization` },
      inLanguage: ["hi", "sa", "en"],
      potentialAction: {
        "@type": "SearchAction",
        target: {
          "@type": "EntryPoint",
          urlTemplate: `${SITE_URL}/scriptures?q={search_term_string}`,
        },
        "query-input": "required name=search_term_string",
      },
    },
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="hi" suppressHydrationWarning>
      <head>
        {/* Preload only critical font files to minimize layout shifts (CLS) and accelerate LCP */}
        <link
          rel="preload"
          href="/fonts/noto-devanagari-400.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/inter-400.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/merriweather-400.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />

        {/* eslint-disable-next-line @next/next/no-sync-scripts */}
        <script dangerouslySetInnerHTML={{ __html: THEME_INIT_SCRIPT }} />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(siteJsonLd) }}
        />
      </head>
      <body className="font-sans bg-dharma-bg text-dharma-text antialiased">
        <ThemeProvider>
          <SpatialLightCursor />
          <a href="#main-content" className="skip-link" lang="en">
            Skip to main content
          </a>
          <SiteNav />
          <div id="main-content" tabIndex={-1} className="outline-none pb-16 md:pb-0">
            <ErrorBoundary name="Main Content">
              <PageTransition>{children}</PageTransition>
            </ErrorBoundary>
          </div>
          <ErrorBoundary name="Floating Companion">
            <FloatingCompanion />
          </ErrorBoundary>
          <TactileLayer />
          <OfflineIndicator />
          <ServiceWorkerRegister />
        </ThemeProvider>
      </body>
    </html>
  );
}
