/**
 * Site-wide share image (generated by `npm run og:build`). Next replaces a
 * parent's whole `openGraph` object when a page sets its own, so pages that
 * define `openGraph` must list this explicitly to keep a preview image.
 */
export const DEFAULT_OG_IMAGE = {
  url: '/og-default.png',
  width: 1200,
  height: 630,
  alt: 'Dharma Granth — Hindu scriptures, verse by verse',
};
