// Generated by `npm run fetch:pinterest` (scripts/fetch-pinterest-pins.ts).
// Do not hand-edit — re-run the script to refresh from your Pinterest boards.

export interface PinterestQuote {
  id: string;
  /** Quote/wisdom text shown over the image — pin title, description, or alt text. */
  quote: string;
  /** Board the pin came from, shown as a small attribution label. */
  board?: string;
  imageUrl: string;
  /** Link back to the original pin on Pinterest. */
  link?: string;
}

export const pinterestQuotes: PinterestQuote[] = [];
